services:
  db:
    image: mariadb:11.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: learn-language
      TZ: Asia/Seoul
    volumes:
      - db:/var/lib/mysql:Z

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8080:80"

  app:
    build: ./
    restart: always
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - db

volumes:
  db:
